plugin.id=com.pmplugin4j.sample.plugin
plugin.class=com.pmplugin4j.sample.plugin.SamplePlugin
plugin.version=${project.version}
plugin.description=MongoDB resource extension sample
plugin.provider=pm-spring-pf4j
plugin.dependencies=
plugin.order=100000
