plugin.id=com.pmplugin4j.sample.security
plugin.class=com.pmplugin4j.sample.security.SecurityPlugin
plugin.version=${project.version}
plugin.description=Plugin authentication sample
plugin.provider=pm-spring-pf4j
plugin.dependencies=
plugin.order=100000
