plugin.id=com.pmplugin4j.sample.basic
plugin.class=com.pmplugin4j.sample.basic.BasicPlugin
plugin.version=${project.version}
plugin.description=Minimal Spring MVC plugin
plugin.provider=pm-spring-pf4j
plugin.dependencies=
plugin.order=100000
