<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>io.github.novohit</groupId><artifactId>pm-spring-pf4j</artifactId><version>0.1.0-alpha.3</version><relativePath>../pom.xml</relativePath></parent>
    <artifactId>pm-pf4j-samples</artifactId><packaging>pom</packaging>
    <properties><maven.deploy.skip>true</maven.deploy.skip></properties>
    <modules><module>sample-host-webmvc</module><module>sample-host-webflux</module><module>sample-plugin-basic</module><module>sample-plugin-data</module><module>sample-plugin-security</module></modules>
</project>
