spring:
  main:
    web-application-type: reactive

pm:
  pf4j:
    directory: plugins
    current-tenant: sample
    tenants:
      sample:
        enabled-plugins:
          - com.pmplugin4j.sample.basic
          - com.pmplugin4j.sample.security
    security:
      filter:
        enabled: true
        allowed-positions: FIRST, LAST
      plugins:
        com.pmplugin4j.sample.security:
          filter:
            allowed-positions: FIRST, LAST
