<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>io.github.novohit</groupId><artifactId>pm-spring-pf4j</artifactId><version>0.1.0-alpha.1</version><relativePath>../pom.xml</relativePath></parent>
    <artifactId>pm-pf4j-spring-boot</artifactId><packaging>pom</packaging>
    <name>PM PF4J Spring Boot</name>
    <properties><maven.deploy.skip>true</maven.deploy.skip></properties>
    <modules><module>pm-pf4j-spring-boot-autoconfigure</module><module>pm-pf4j-spring-boot-starter</module></modules>
</project>
